namespace Jobsite.Modules.Profiles.Application.DTOs;

/// <summary>Structured resume data extracted by the AI Service.</summary>
public sealed class AiResumeParseResult
{
    /// <summary>Skills with proficiency levels and years.</summary>
    public List<AiExtractedSkill>? Skills { get; init; }

    /// <summary>Work experience entries.</summary>
    public List<AiExperience>? Experience { get; init; }

    /// <summary>Education entries.</summary>
    public List<AiEducation>? Education { get; init; }

    /// <summary>Professional certifications.</summary>
    public List<string>? Certifications { get; init; }

    /// <summary>Brief professional summary generated by AI.</summary>
    public string? Summary { get; init; }
}

public sealed class AiExtractedSkill
{
    public required string Name { get; init; }
    public string? Level { get; init; }
    public int? Years { get; init; }
}

public sealed class AiExperience
{
    public required string Title { get; init; }
    public required string Company { get; init; }
    public string? StartDate { get; init; }
    public string? EndDate { get; init; }
    public string? Description { get; init; }
}

public sealed class AiEducation
{
    public required string Degree { get; init; }
    public required string Institution { get; init; }
    public string? StartDate { get; init; }
    public string? EndDate { get; init; }
    public string? Field { get; init; }
}
