// <auto-generated />
using System;
using Jobsite.Modules.Profiles.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Jobsite.Modules.Profiles.Infrastructure.Migrations
{
    [DbContext(typeof(ProfilesDbContext))]
    partial class ProfilesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Jobsite.Modules.Profiles.Domain.Entities.ApplicantProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Documents")
                        .HasColumnType("jsonb")
                        .HasColumnName("documents");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("ProfileCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("profile_completed_at");

                    b.Property<string>("Skills")
                        .HasColumnType("jsonb")
                        .HasColumnName("skills");

                    b.Property<string>("SocialLinks")
                        .HasColumnType("jsonb")
                        .HasColumnName("social_links");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_applicant_profiles");

                    b.HasIndex("City", "Country")
                        .HasDatabaseName("ix_applicant_profiles_city_country");

                    b.ToTable("applicant_profiles", "profiles");
                });

            modelBuilder.Entity("Jobsite.Modules.Profiles.Domain.Entities.Resume", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AiParsedContent")
                        .HasColumnType("jsonb")
                        .HasColumnName("ai_parsed_content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ExtractedSkills")
                        .HasColumnType("jsonb")
                        .HasColumnName("extracted_skills");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size_bytes");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("file_type");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("file_url");

                    b.Property<bool>("IsLatest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_latest");

                    b.Property<bool>("IsParsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_parsed");

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("original_filename");

                    b.Property<string>("ParseError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("parse_error");

                    b.Property<DateTime?>("ParsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("parsed_at");

                    b.Property<string>("ParsedText")
                        .HasColumnType("text")
                        .HasColumnName("parsed_text");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_resumes");

                    b.HasIndex("IsParsed")
                        .HasDatabaseName("ix_resumes_is_parsed");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_resumes_user_id");

                    b.HasIndex("UserId", "IsLatest")
                        .HasDatabaseName("ix_resumes_user_id_is_latest");

                    b.ToTable("resumes", "profiles", t =>
                        {
                            t.HasCheckConstraint("chk_resumes_file_type", "file_type IN ('PDF', 'DOCX')");
                        });
                });

            modelBuilder.Entity("Jobsite.Modules.Profiles.Domain.Entities.Resume", b =>
                {
                    b.HasOne("Jobsite.Modules.Profiles.Domain.Entities.ApplicantProfile", "ApplicantProfile")
                        .WithMany("Resumes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_resumes_applicant_profiles_user_id");

                    b.Navigation("ApplicantProfile");
                });

            modelBuilder.Entity("Jobsite.Modules.Profiles.Domain.Entities.ApplicantProfile", b =>
                {
                    b.Navigation("Resumes");
                });
#pragma warning restore 612, 618
        }
    }
}
