// <auto-generated />
using System;
using Jobsite.Modules.Matching.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Jobsite.Modules.Matching.Infrastructure.Migrations
{
    [DbContext(typeof(MatchingDbContext))]
    [Migration("20260408062442_InitialMatchingSchema")]
    partial class InitialMatchingSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Jobsite.Modules.Matching.Domain.Entities.CandidateMatch", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<Guid>("ApplicantUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("applicant_user_id");

                    b.Property<DateTime?>("AssessmentCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assessment_completed_at");

                    b.Property<decimal?>("AssessmentScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("assessment_score");

                    b.Property<decimal>("CompositeScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("composite_score");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("JobPostingId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_posting_id");

                    b.Property<string>("MatchStrength")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("match_strength");

                    b.Property<int?>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<DateTime>("ScreeningCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("screening_completed_at");

                    b.Property<decimal>("ScreeningScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("screening_score");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("ApplicationId")
                        .HasName("pk_candidate_matches");

                    b.HasIndex("ApplicantUserId")
                        .HasDatabaseName("ix_candidate_matches_applicant_user_id");

                    b.HasIndex("CompositeScore")
                        .HasDatabaseName("ix_candidate_matches_composite_score");

                    b.HasIndex("JobPostingId")
                        .HasDatabaseName("ix_candidate_matches_job_posting_id");

                    b.HasIndex("MatchStrength")
                        .HasDatabaseName("ix_candidate_matches_match_strength");

                    b.ToTable("candidate_matches", "matching", t =>
                        {
                            t.HasCheckConstraint("chk_matches_match_strength", "match_strength IS NULL OR match_strength IN ('Strong', 'Good', 'Moderate', 'Weak')");
                        });
                });

            modelBuilder.Entity("Jobsite.Modules.Matching.Domain.Entities.Shortlist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalized_at");

                    b.Property<Guid?>("FinalizedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("finalized_by");

                    b.Property<string>("GeneratedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("generated_by");

                    b.Property<Guid>("JobPostingId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_posting_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("TotalCandidates")
                        .HasColumnType("integer")
                        .HasColumnName("total_candidates");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_shortlists");

                    b.HasIndex("JobPostingId")
                        .HasDatabaseName("ix_shortlists_job_posting_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_shortlists_status");

                    b.ToTable("shortlists", "matching", t =>
                        {
                            t.HasCheckConstraint("chk_shortlists_status", "status IN ('Draft', 'Finalized')");
                        });
                });

            modelBuilder.Entity("Jobsite.Modules.Matching.Domain.Entities.ShortlistCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<Guid>("ApplicantUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("applicant_user_id");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<decimal>("CompositeScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("composite_score");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<Guid>("ShortlistId")
                        .HasColumnType("uuid")
                        .HasColumnName("shortlist_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("source");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_shortlist_candidates");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_shortlist_candidates_application_id");

                    b.HasIndex("ShortlistId", "ApplicationId")
                        .IsUnique()
                        .HasDatabaseName("uq_shortlist_candidates_shortlist_app");

                    b.ToTable("shortlist_candidates", "matching", t =>
                        {
                            t.HasCheckConstraint("chk_shortlist_candidates_source", "source IN ('Algorithm', 'Manual')");
                        });
                });

            modelBuilder.Entity("Jobsite.Modules.Matching.Domain.Entities.ShortlistCandidate", b =>
                {
                    b.HasOne("Jobsite.Modules.Matching.Domain.Entities.Shortlist", "Shortlist")
                        .WithMany("Candidates")
                        .HasForeignKey("ShortlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_shortlist_candidates_shortlists_shortlist_id");

                    b.Navigation("Shortlist");
                });

            modelBuilder.Entity("Jobsite.Modules.Matching.Domain.Entities.Shortlist", b =>
                {
                    b.Navigation("Candidates");
                });
#pragma warning restore 612, 618
        }
    }
}
