// <auto-generated />
using System;
using Jobsite.Modules.Recruitment.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Jobsite.Modules.Recruitment.Infrastructure.Migrations
{
    [DbContext(typeof(RecruitmentDbContext))]
    [Migration("20260408062400_InitialRecruitmentSchema")]
    partial class InitialRecruitmentSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Jobsite.Modules.Recruitment.Domain.Entities.Application", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ApplicantId")
                        .HasColumnType("uuid")
                        .HasColumnName("applicant_id");

                    b.Property<string>("CoverLetterUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("cover_letter_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("JobPostingId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_posting_id");

                    b.Property<string>("RejectedAtStage")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rejected_at_stage");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<Guid>("ResumeId")
                        .HasColumnType("uuid")
                        .HasColumnName("resume_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("WithdrawnAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("withdrawn_at");

                    b.HasKey("Id")
                        .HasName("pk_applications");

                    b.HasIndex("ApplicantId")
                        .HasDatabaseName("ix_applications_applicant_id");

                    b.HasIndex("JobPostingId")
                        .HasDatabaseName("ix_applications_job_posting_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_applications_status");

                    b.HasIndex("SubmittedAt")
                        .HasDatabaseName("ix_applications_submitted_at");

                    b.HasIndex("ApplicantId", "JobPostingId")
                        .IsUnique()
                        .HasDatabaseName("uq_applications_applicant_job");

                    b.ToTable("applications", "recruitment", t =>
                        {
                            t.HasCheckConstraint("chk_applications_rejected_at_stage", "rejected_at_stage IS NULL OR rejected_at_stage IN ('Screening', 'Assessment', 'Shortlisted', 'FinalInterview', 'Offered')");

                            t.HasCheckConstraint("chk_applications_status", "status IN ('Submitted', 'Screening', 'Assessment', 'Shortlisted', 'FinalInterview', 'Offered', 'Hired', 'Rejected', 'Withdrawn')");
                        });
                });

            modelBuilder.Entity("Jobsite.Modules.Recruitment.Domain.Entities.ClientCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contact_name");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("industry");

                    b.Property<bool>("IsAnonymous")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_anonymous");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Website")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_client_companies");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_client_companies_name");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_client_companies_status");

                    b.ToTable("client_companies", "recruitment", t =>
                        {
                            t.HasCheckConstraint("chk_client_companies_status", "status IN ('Active', 'Inactive')");
                        });
                });

            modelBuilder.Entity("Jobsite.Modules.Recruitment.Domain.Entities.JobEvaluationCriteria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("category");

                    b.Property<string>("Configuration")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("configuration");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("EvaluationMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("evaluation_method");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_required");

                    b.Property<Guid>("JobPostingId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_posting_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_job_evaluation_criteria");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_criteria_category");

                    b.HasIndex("JobPostingId")
                        .HasDatabaseName("ix_criteria_job_posting_id");

                    b.ToTable("job_evaluation_criteria", "recruitment", t =>
                        {
                            t.HasCheckConstraint("chk_criteria_category", "category IN ('Skill', 'Experience', 'Certification', 'Education', 'Location', 'Custom')");

                            t.HasCheckConstraint("chk_criteria_evaluation_method", "evaluation_method IN ('ExactMatch', 'RangeMatch', 'SemanticSimilarity')");
                        });
                });

            modelBuilder.Entity("Jobsite.Modules.Recruitment.Domain.Entities.JobPosting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<Guid?>("ClientCompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_company_id");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTime?>("ClosesAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closes_at");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("department");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("employment_type");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("location_type");

                    b.Property<Guid>("PostedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("posted_by");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Requirements")
                        .HasColumnType("text")
                        .HasColumnName("requirements");

                    b.Property<string>("SalaryCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("salary_currency");

                    b.Property<decimal?>("SalaryMax")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("salary_max");

                    b.Property<decimal?>("SalaryMin")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("salary_min");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_job_postings");

                    b.HasIndex("ClientCompanyId")
                        .HasDatabaseName("ix_job_postings_client_company");

                    b.HasIndex("PostedBy")
                        .HasDatabaseName("ix_job_postings_posted_by");

                    b.HasIndex("PublishedAt")
                        .HasDatabaseName("ix_job_postings_published_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_job_postings_status");

                    b.HasIndex("City", "Country")
                        .HasDatabaseName("ix_job_postings_location");

                    b.ToTable("job_postings", "recruitment", t =>
                        {
                            t.HasCheckConstraint("chk_job_postings_employment_type", "employment_type IN ('FullTime', 'PartTime', 'Contract', 'Temporary', 'Internship')");

                            t.HasCheckConstraint("chk_job_postings_location_type", "location_type IN ('OnSite', 'Remote', 'Hybrid')");

                            t.HasCheckConstraint("chk_job_postings_status", "status IN ('Draft', 'Published', 'Closed')");
                        });
                });

            modelBuilder.Entity("Jobsite.Modules.Recruitment.Domain.Entities.JobScreeningQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("ExpectedAnswer")
                        .HasColumnType("jsonb")
                        .HasColumnName("expected_answer");

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_required");

                    b.Property<Guid>("JobPostingId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_posting_id");

                    b.Property<string>("Options")
                        .HasColumnType("jsonb")
                        .HasColumnName("options");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("question_text");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("question_type");

                    b.Property<string>("Timing")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("timing");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_job_screening_questions");

                    b.HasIndex("JobPostingId")
                        .HasDatabaseName("ix_questions_job_posting_id");

                    b.HasIndex("Timing")
                        .HasDatabaseName("ix_questions_timing");

                    b.ToTable("job_screening_questions", "recruitment", t =>
                        {
                            t.HasCheckConstraint("chk_questions_question_type", "question_type IN ('FreeText', 'MultipleChoice', 'YesNo')");

                            t.HasCheckConstraint("chk_questions_timing", "timing IN ('AtApplication', 'AfterScreening')");
                        });
                });

            modelBuilder.Entity("Jobsite.Modules.Recruitment.Domain.Entities.Application", b =>
                {
                    b.HasOne("Jobsite.Modules.Recruitment.Domain.Entities.JobPosting", "JobPosting")
                        .WithMany("Applications")
                        .HasForeignKey("JobPostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_applications_job_postings_job_posting_id");

                    b.Navigation("JobPosting");
                });

            modelBuilder.Entity("Jobsite.Modules.Recruitment.Domain.Entities.JobEvaluationCriteria", b =>
                {
                    b.HasOne("Jobsite.Modules.Recruitment.Domain.Entities.JobPosting", "JobPosting")
                        .WithMany("Criteria")
                        .HasForeignKey("JobPostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_evaluation_criteria_job_postings_job_posting_id");

                    b.Navigation("JobPosting");
                });

            modelBuilder.Entity("Jobsite.Modules.Recruitment.Domain.Entities.JobPosting", b =>
                {
                    b.HasOne("Jobsite.Modules.Recruitment.Domain.Entities.ClientCompany", "ClientCompany")
                        .WithMany("JobPostings")
                        .HasForeignKey("ClientCompanyId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_job_postings_client_companies_client_company_id");

                    b.Navigation("ClientCompany");
                });

            modelBuilder.Entity("Jobsite.Modules.Recruitment.Domain.Entities.JobScreeningQuestion", b =>
                {
                    b.HasOne("Jobsite.Modules.Recruitment.Domain.Entities.JobPosting", "JobPosting")
                        .WithMany("Questions")
                        .HasForeignKey("JobPostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_screening_questions_job_postings_job_posting_id");

                    b.Navigation("JobPosting");
                });

            modelBuilder.Entity("Jobsite.Modules.Recruitment.Domain.Entities.ClientCompany", b =>
                {
                    b.Navigation("JobPostings");
                });

            modelBuilder.Entity("Jobsite.Modules.Recruitment.Domain.Entities.JobPosting", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Criteria");

                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
