// <auto-generated />
using System;
using Jobsite.Modules.HRWorkflows.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Jobsite.Modules.HRWorkflows.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HRWorkflowsDbContext))]
    [Migration("20260405063051_InitialHRWorkflowsSchema")]
    partial class InitialHRWorkflowsSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Jobsite.Modules.HRWorkflows.Domain.Entities.FinalInterview", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at");

                    b.Property<Guid?>("DecidedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("decided_by");

                    b.Property<string>("DecisionNotes")
                        .HasColumnType("text")
                        .HasColumnName("decision_notes");

                    b.Property<int>("DurationMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60)
                        .HasColumnName("duration_minutes");

                    b.Property<string>("InterviewType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("interview_type");

                    b.Property<string>("Location")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("location");

                    b.Property<string>("OverallRecommendation")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("overall_recommendation");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<Guid>("ScheduledBy")
                        .HasColumnType("uuid")
                        .HasColumnName("scheduled_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("ApplicationId")
                        .HasName("pk_final_interviews");

                    b.HasIndex("OverallRecommendation")
                        .HasDatabaseName("ix_final_interviews_recommendation");

                    b.HasIndex("ScheduledAt")
                        .HasDatabaseName("ix_final_interviews_scheduled_at");

                    b.HasIndex("ScheduledBy")
                        .HasDatabaseName("ix_final_interviews_scheduled_by");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_final_interviews_status");

                    b.ToTable("final_interviews", "hr_workflows", t =>
                        {
                            t.HasCheckConstraint("chk_final_interviews_interview_type", "interview_type IN ('InPerson', 'Video', 'Phone')");

                            t.HasCheckConstraint("chk_final_interviews_recommendation", "overall_recommendation IS NULL OR overall_recommendation IN ('StrongHire', 'Hire', 'NoHire', 'StrongNoHire')");

                            t.HasCheckConstraint("chk_final_interviews_status", "status IN ('Scheduled', 'InProgress', 'Completed', 'Cancelled', 'NoShow')");
                        });
                });

            modelBuilder.Entity("Jobsite.Modules.HRWorkflows.Domain.Entities.InterviewPanelist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Concerns")
                        .HasColumnType("text")
                        .HasColumnName("concerns");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime?>("FeedbackSubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("feedback_submitted_at");

                    b.Property<Guid>("InterviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("interview_id");

                    b.Property<Guid>("InterviewerId")
                        .HasColumnType("uuid")
                        .HasColumnName("interviewer_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(3,1)")
                        .HasColumnName("rating");

                    b.Property<string>("Recommendation")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("recommendation");

                    b.Property<string>("Strengths")
                        .HasColumnType("text")
                        .HasColumnName("strengths");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_interview_panelists");

                    b.HasIndex("InterviewId")
                        .HasDatabaseName("ix_panelists_interview_id");

                    b.HasIndex("InterviewerId")
                        .HasDatabaseName("ix_panelists_interviewer_id");

                    b.HasIndex("InterviewId", "FeedbackSubmittedAt")
                        .HasDatabaseName("ix_panelists_feedback_pending");

                    b.HasIndex("InterviewId", "InterviewerId")
                        .IsUnique()
                        .HasDatabaseName("uq_panelists_interview_interviewer");

                    b.ToTable("interview_panelists", "hr_workflows", t =>
                        {
                            t.HasCheckConstraint("chk_panelists_rating", "rating IS NULL OR (rating >= 1.0 AND rating <= 5.0)");

                            t.HasCheckConstraint("chk_panelists_recommendation", "recommendation IS NULL OR recommendation IN ('StrongHire', 'Hire', 'NoHire', 'StrongNoHire')");
                        });
                });

            modelBuilder.Entity("Jobsite.Modules.HRWorkflows.Domain.Entities.JobOffer", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<string>("AdditionalTerms")
                        .HasColumnType("text")
                        .HasColumnName("additional_terms");

                    b.Property<string>("Benefits")
                        .HasColumnType("text")
                        .HasColumnName("benefits");

                    b.Property<Guid?>("ClientCompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_company_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DeclineReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("decline_reason");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("employment_type");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime?>("ExtendedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("extended_at");

                    b.Property<Guid>("ExtendedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("extended_by");

                    b.Property<string>("OfferLetterUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("offer_letter_url");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(12,2)")
                        .HasColumnName("salary");

                    b.Property<string>("SalaryCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("salary_currency");

                    b.Property<string>("SalaryPeriod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("salary_period");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("WithdrawalReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("withdrawal_reason");

                    b.Property<DateTime?>("WithdrawnAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("withdrawn_at");

                    b.HasKey("ApplicationId")
                        .HasName("pk_job_offers");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_job_offers_expires_at");

                    b.HasIndex("ExtendedBy")
                        .HasDatabaseName("ix_job_offers_extended_by");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_job_offers_status");

                    b.ToTable("job_offers", "hr_workflows", t =>
                        {
                            t.HasCheckConstraint("chk_job_offers_employment_type", "employment_type IN ('FullTime', 'PartTime', 'Contract', 'Temporary')");

                            t.HasCheckConstraint("chk_job_offers_salary_period", "salary_period IN ('Annual', 'Monthly', 'Hourly')");

                            t.HasCheckConstraint("chk_job_offers_status", "status IN ('Draft', 'Pending', 'Accepted', 'Declined', 'Withdrawn', 'Expired')");
                        });
                });

            modelBuilder.Entity("Jobsite.Modules.HRWorkflows.Domain.Entities.InterviewPanelist", b =>
                {
                    b.HasOne("Jobsite.Modules.HRWorkflows.Domain.Entities.FinalInterview", "Interview")
                        .WithMany("Panelists")
                        .HasForeignKey("InterviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_interview_panelists_final_interviews_interview_id");

                    b.Navigation("Interview");
                });

            modelBuilder.Entity("Jobsite.Modules.HRWorkflows.Domain.Entities.FinalInterview", b =>
                {
                    b.Navigation("Panelists");
                });
#pragma warning restore 612, 618
        }
    }
}
