// <auto-generated />
using System;
using Jobsite.Modules.Screening.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Jobsite.Modules.Screening.Infrastructure.Migrations
{
    [DbContext(typeof(ScreeningDbContext))]
    partial class ScreeningDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Jobsite.Modules.Screening.Domain.Entities.ScreeningQuestionResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<string>("ResponseData")
                        .HasColumnType("jsonb")
                        .HasColumnName("response_data");

                    b.Property<string>("ResponseText")
                        .HasColumnType("text")
                        .HasColumnName("response_text");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("score");

                    b.Property<string>("ScoreReasoning")
                        .HasColumnType("text")
                        .HasColumnName("score_reasoning");

                    b.Property<string>("ScoreResult")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("score_result");

                    b.Property<DateTime?>("ScoredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scored_at");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_screening_question_responses");

                    b.HasIndex("ApplicationId")
                        .HasDatabaseName("ix_question_responses_application_id");

                    b.HasIndex("ApplicationId", "QuestionId")
                        .IsUnique()
                        .HasDatabaseName("uq_question_responses_app_question");

                    b.ToTable("screening_question_responses", "screening", t =>
                        {
                            t.HasCheckConstraint("chk_question_responses_score_result", "score_result IS NULL OR score_result IN ('MeetsRequirement', 'PartialMatch', 'Missing')");
                        });
                });

            modelBuilder.Entity("Jobsite.Modules.Screening.Domain.Entities.ScreeningResult", b =>
                {
                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uuid")
                        .HasColumnName("application_id");

                    b.Property<string>("AiCriteriaScoreBreakdown")
                        .HasColumnType("jsonb")
                        .HasColumnName("ai_criteria_score_breakdown");

                    b.Property<decimal?>("AiOverallScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("ai_overall_score");

                    b.Property<decimal?>("AssessmentScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("assessment_score");

                    b.Property<decimal>("AutoAdvanceThreshold")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("auto_advance_threshold");

                    b.Property<decimal>("AutoRejectThreshold")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("auto_reject_threshold");

                    b.Property<string>("CandidateFeedback")
                        .HasColumnType("jsonb")
                        .HasColumnName("candidate_feedback");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CriteriaScoreBreakdown")
                        .HasColumnType("jsonb")
                        .HasColumnName("criteria_score_breakdown");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("MatchStrength")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("match_strength");

                    b.Property<string>("Outcome")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("outcome");

                    b.Property<decimal?>("OverallScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("overall_score");

                    b.Property<string>("QuestionScoreBreakdown")
                        .HasColumnType("jsonb")
                        .HasColumnName("question_score_breakdown");

                    b.Property<string>("ReviewNotes")
                        .HasColumnType("text")
                        .HasColumnName("review_notes");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("ApplicationId")
                        .HasName("pk_screening_results");

                    b.HasIndex("MatchStrength")
                        .HasDatabaseName("ix_screening_results_match_strength");

                    b.HasIndex("Outcome")
                        .HasDatabaseName("ix_screening_results_outcome");

                    b.HasIndex("OverallScore")
                        .HasDatabaseName("ix_screening_results_overall_score");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_screening_results_status");

                    b.ToTable("screening_results", "screening", t =>
                        {
                            t.HasCheckConstraint("chk_screening_results_match_strength", "match_strength IS NULL OR match_strength IN ('Strong', 'Good', 'Moderate', 'Weak')");

                            t.HasCheckConstraint("chk_screening_results_outcome", "outcome IS NULL OR outcome IN ('AutoAdvanced', 'AutoRejected', 'ManualReview', 'ManuallyAdvanced', 'ManuallyRejected')");

                            t.HasCheckConstraint("chk_screening_results_status", "status IN ('Pending', 'InProgress', 'Completed', 'Failed')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
