using FluentAssertions;
using Jobsite.Modules.Auth.Domain.Constants;
using Jobsite.Modules.Auth.Domain.Entities;
using Microsoft.EntityFrameworkCore;

namespace Jobsite.IntegrationTests.Auth;

/// <summary>
/// Integration tests validating AuthDbContext schema creation, table mapping,
/// default values, and relationship behavior against a real PostgreSQL container.
/// </summary>
[Collection("Auth")]
public sealed class AuthDbContextTests : IAsyncLifetime
{
    private readonly AuthIntegrationFixture _fixture;

    public AuthDbContextTests(AuthIntegrationFixture fixture)
    {
        _fixture = fixture;
    }

    public Task InitializeAsync() => _fixture.ResetDataAsync();
    public Task DisposeAsync() => Task.CompletedTask;

    [Fact]
    public async Task Schema_AuthSchemaExists()
    {
        // Act — query the database directly for the auth schema
        await using Npgsql.NpgsqlConnection conn = new(_fixture.ConnectionString);
        await conn.OpenAsync();

        await using Npgsql.NpgsqlCommand cmd = conn.CreateCommand();
        cmd.CommandText = "SELECT schema_name FROM information_schema.schemata WHERE schema_name = 'auth'";
        object? result = await cmd.ExecuteScalarAsync();
        string? schemaName = result?.ToString();

        // Assert
        schemaName.Should().Be("auth");
    }

    [Fact]
    public async Task Users_DefaultValues_AppliedByDatabase()
    {
        // Arrange
        User user = new()
        {
            Email = "defaults@test.com",
            PasswordHash = "somehash",
            Role = UserRole.Applicant,
            Status = UserStatus.Active,
            FirstName = "Default",
            LastName = "Test"
        };

        // Act
        _fixture.DbContext.Users.Add(user);
        await _fixture.DbContext.SaveChangesAsync();

        // Detach and re-query to get database-generated values
        _fixture.DbContext.ChangeTracker.Clear();
        User? persisted = await _fixture.DbContext.Users
            .AsNoTracking()
            .FirstOrDefaultAsync(u => u.Email == "defaults@test.com");

        // Assert
        persisted.Should().NotBeNull();
        persisted!.Id.Should().NotBe(Guid.Empty, "id should be generated by database");
        persisted.EmailVerified.Should().BeFalse("email_verified should default to false");
        persisted.CreatedAt.Should().BeCloseTo(DateTime.UtcNow, TimeSpan.FromSeconds(10));
        persisted.UpdatedAt.Should().BeCloseTo(DateTime.UtcNow, TimeSpan.FromSeconds(10));
    }

    [Fact]
    public async Task Users_ExternalLoginCascade_DeletesLoginWhenUserDeleted()
    {
        // Arrange
        User user = IntegrationTestData.CreateUser(email: "cascadelogin@test.com");
        user.ExternalLogins.Add(new UserExternalLogin
        {
            Provider = ExternalLoginProvider.Google,
            ProviderSubjectId = "cascade-subject-id",
            ProviderEmail = "cascadelogin@test.com",
            LinkedAt = DateTime.UtcNow
        });
        _fixture.DbContext.Users.Add(user);
        await _fixture.DbContext.SaveChangesAsync();

        Guid loginId = user.ExternalLogins[0].Id;

        // Act — delete the user
        User? trackedUser = await _fixture.DbContext.Users
            .FirstOrDefaultAsync(u => u.Id == user.Id);
        _fixture.DbContext.Users.Remove(trackedUser!);
        await _fixture.DbContext.SaveChangesAsync();

        // Assert
        UserExternalLogin? orphaned = await _fixture.DbContext.UserExternalLogins
            .AsNoTracking()
            .FirstOrDefaultAsync(e => e.Id == loginId);

        orphaned.Should().BeNull("external logins should be cascade deleted with user");
    }

    [Fact]
    public async Task ExternalLogins_UniqueProviderPerUser_EnforcedByDatabase()
    {
        // Arrange
        User user = IntegrationTestData.CreateUser(email: "dupeprovider@test.com");
        user.ExternalLogins.Add(new UserExternalLogin
        {
            Provider = ExternalLoginProvider.Google,
            ProviderSubjectId = "subject-1",
            ProviderEmail = "dupeprovider@test.com",
            LinkedAt = DateTime.UtcNow
        });
        _fixture.DbContext.Users.Add(user);
        await _fixture.DbContext.SaveChangesAsync();

        // Add another login with the same provider + subject
        UserExternalLogin duplicate = new()
        {
            UserId = user.Id,
            Provider = ExternalLoginProvider.Google,
            ProviderSubjectId = "subject-1",
            ProviderEmail = "dupeprovider@test.com",
            LinkedAt = DateTime.UtcNow
        };
        _fixture.DbContext.UserExternalLogins.Add(duplicate);

        // Act
        Func<Task> act = async () => await _fixture.DbContext.SaveChangesAsync();

        // Assert — unique index should reject duplicate provider+subject
        await act.Should().ThrowAsync<DbUpdateException>();

        _fixture.DbContext.ChangeTracker.Clear();
    }

    [Fact]
    public async Task Users_NullablePasswordHash_AllowsOAuthOnlyUsers()
    {
        // Arrange — OAuth-only user has no password
        User user = IntegrationTestData.CreateUser(email: "oauthonly@test.com");
        user.PasswordHash = null;

        // Act
        _fixture.DbContext.Users.Add(user);
        await _fixture.DbContext.SaveChangesAsync();

        // Assert
        _fixture.DbContext.ChangeTracker.Clear();
        User? persisted = await _fixture.DbContext.Users
            .AsNoTracking()
            .FirstOrDefaultAsync(u => u.Email == "oauthonly@test.com");

        persisted.Should().NotBeNull();
        persisted!.PasswordHash.Should().BeNull();
    }
}
